### ISSUE TITLE
saytning footer qismidagi iconkalar 

### ISSUE THREAD

**Issue by IbragimovOlimjon** [frontendoniyorbek/n-24#4]
![image](https://user-images.githubusercontent.com/98340831/158362225-1c4431fa-8a3a-4720-8a77-8665353a9ad0.png)
block bilan bog'liq muammo oshiqcha joylarni olib tashlash kerak boladi

**Comment by frontendoniyorbek** [comment]
bo`ldi uni ham to`g`irlab qo`ydim
