### ISSUE TITLE
Footerning eng pastki qismidagi iconlar

### ISSUE THREAD

**Issue by IbragimovOlimjon** [frontendoniyorbek/n-24#5]
![image](https://user-images.githubusercontent.com/98340831/158365126-b646a234-2f73-409b-b0ae-044883cf0484.png)
saytlarga olib boruvchi logotiplarimiz orasida facebook logotipi qo'yilmagan

**Comment by frontendoniyorbek** [comment]
bo`ldi to`g`irlab qo`ydim
