### ISSUE TITLE
Site-logo ga no'tog'ri height berilgan

### ISSUE THREAD

**Issue by Azizbek-Boyhamdamov** [frontendoniyorbek/n-24#6]
https://github.com/frontendoniyorbek/n-24/blob/e0725af33916ac3447ef5f377fae976078c0049c/index.html#L26
![Screenshot_31](https://user-images.githubusercontent.com/99174734/158441775-f62379ff-e170-4539-8812-3a06cc65fefc.png)
Logo rasmi height 19 , html da esa siz uni 28 qilib qo'yabsiz , bu logoni bo'yini o'sishiga olib kelyabdi

**Comment by frontendoniyorbek** [comment]
bo``ldi
