### ISSUE TITLE
.site-footer-container width : 1000px ; bo'lishi kerak

### ISSUE THREAD

**Issue by Azizbek-Boyhamdamov** [frontendoniyorbek/n-24#7]
![Screenshot_32](https://user-images.githubusercontent.com/99174734/158443322-4d26acf1-fed1-4079-8d8e-5537e8b819e8.png)
footerni o'rab turuvchi container 1000px bo'lishi kerak

**Comment by frontendoniyorbek** [comment]
men shunga "max-width:1240px" moslaganman sayitni
